/**
 * File: trusted_coordinator_manifest.ts
 * Description: Standard scaffold manifest for trusted runtime coordinators.
 */

import type { TrustedRuntimeCoordinatorScaffoldDescriptor } from './trusted_runtime_coordinator.ts';

export const TRUSTED_COORDINATOR_SCAFFOLD_MANIFEST = [
  {
    coordinator_id: 'trusted_dispatch_coordinator.v0',
    coordinator_kind: 'dispatch',
    public_object_name: 'trustedDispatchCoordinator',
    public_import_path: '@runtime/trusted_coordinators/trusted_dispatch_coordinator',
    runtime_path: 'runtime/trusted_coordinators/trusted_dispatch_coordinator',
    structure: 'foldered_gated',
    expected_methods: [
      { method_name: 'normalizeRequest', notes: 'Validates and normalizes interface/API events into trusted runtime requests.' },
      { method_name: 'preflightClientIntent', notes: 'Checks route/intent enrollment before mutation preparation.' },
      { method_name: 'prepareEnrolledMutationWrite', notes: 'Runs an enrolled mutation prepare request through the dispatch-owned coordinator write pipeline.' },
      { method_name: 'finalizeEnrolledMutationWrite', notes: 'Runs an enrolled mutation finalize request through Certification, Verification, and Archive.' },
      { method_name: 'listEnrollments', notes: 'Lists registered client/API ingress enrollments.' },
      { method_name: 'auditReadiness', notes: 'Audits dispatch intake enrollment coverage.' },
    ],
    notes: 'Canonical runtime front desk for dispatch intake. Currently delegates to the compatibility Trusted Request Coordinator implementation.',
  },
  {
    coordinator_id: 'trusted_request_coordinator.v0',
    coordinator_kind: 'request',
    public_object_name: 'trustedRequestCoordinator',
    public_import_path: '@runtime/trusted_coordinators/trusted_request_coordinator',
    runtime_path: 'runtime/trusted_coordinators/trusted_request_coordinator',
    structure: 'foldered_gated',
    expected_methods: [
      { method_name: 'normalizeRequest', notes: 'Validates and normalizes interface/API signals into trusted runtime requests.' },
      { method_name: 'preflightClientIntent', notes: 'Checks route/intent enrollment before mutation preparation.' },
      { method_name: 'listEnrollments', notes: 'Lists registered client/API ingress enrollments.' },
      { method_name: 'auditReadiness', notes: 'Audits request intake enrollment coverage.' },
    ],
    notes: 'Compatibility name for the runtime dispatch front desk. New code should prefer Trusted Dispatch Coordinator.',
  },
  {
    coordinator_id: 'trusted_definition_coordinator.v0',
    coordinator_kind: 'definition',
    public_object_name: 'trustedDefinitionCoordinator',
    public_import_path: '@runtime/trusted_coordinators/trusted_definition_coordinator/index.ts',
    runtime_path: 'runtime/trusted_coordinators/trusted_definition_coordinator',
    structure: 'foldered_gated',
    expected_methods: [
      { method_name: 'resolveContext', notes: 'Resolves active trusted definition context.' },
      { method_name: 'resolvePacketDefinition', notes: 'Resolves a trusted packet definition.' },
      { method_name: 'resolveDefinitionPart', notes: 'Resolves an active trusted definition part.' },
      { method_name: 'compileRuntimeView', notes: 'Compiles coordinator-facing definition runtime view.' },
      { method_name: 'auditReadiness', notes: 'Audits definition readiness.' },
    ],
    notes: 'Definition source of truth for active trusted definition material.',
  },
  {
    coordinator_id: 'trusted_regulation_coordinator.v0',
    coordinator_kind: 'regulation',
    public_object_name: 'trustedRegulationCoordinator',
    public_import_path: '@runtime/trusted_coordinators/trusted_regulation_coordinator/index.ts',
    runtime_path: 'runtime/trusted_coordinators/trusted_regulation_coordinator',
    structure: 'foldered_gated',
    expected_methods: [
      { method_name: 'resolveContext', notes: 'Resolves policy/write-gate regulation context.' },
      { method_name: 'resolvePolicyContext', notes: 'Resolves policy requirements and verdict context.' },
      { method_name: 'resolveWritePolicyGate', notes: 'Resolves the write-policy gate.' },
      { method_name: 'listRequirements', notes: 'Lists regulation requirements.' },
      { method_name: 'auditReadiness', notes: 'Audits regulation readiness.' },
    ],
    notes: 'Rule envelope coordinator. It does not own structural defaults or build dependencies.',
  },
  {
    coordinator_id: 'trusted_planning_coordinator.v0',
    coordinator_kind: 'planning',
    public_object_name: 'trustedPlanningCoordinator',
    public_import_path: '@runtime/trusted_coordinators/trusted_planning_coordinator/index.ts',
    runtime_path: 'runtime/trusted_coordinators/trusted_planning_coordinator',
    structure: 'foldered_gated',
    expected_methods: [
      { method_name: 'resolveOperationPlan', notes: 'Compiles intent into a build/operation plan.' },
      { method_name: 'resolveDefaultPlan', notes: 'Resolves planned defaults.' },
      { method_name: 'resolveDependencyPlan', notes: 'Resolves structural dependencies.' },
      { method_name: 'selectBuilderDescriptor', notes: 'Selects the builder descriptor for a plan node.' },
      { method_name: 'auditReadiness', notes: 'Audits planning readiness.' },
    ],
    notes: 'Operation compiler and recursive blueprint owner.',
  },
  {
    coordinator_id: 'trusted_building_coordinator.v0',
    coordinator_kind: 'building',
    public_object_name: 'trustedBuildingCoordinator',
    public_import_path: '@runtime/trusted_coordinators/trusted_building_coordinator/index.ts',
    runtime_path: 'runtime/trusted_coordinators/trusted_building_coordinator',
    structure: 'foldered_gated',
    expected_methods: [
      { method_name: 'buildFromOperationPlan', notes: 'Materializes packet candidates from trusted operation plans.' },
      { method_name: 'buildPacketBodyCandidate', notes: 'Builds a single packet candidate node from a plan node.' },
      { method_name: 'buildPacketTypeBodyCandidate', notes: 'Runs local body builders for runtime-ready typed body candidates.' },
      { method_name: 'buildDefinitionPartCandidates', notes: 'Builds Definition part body candidates for reseed readiness.' },
      { method_name: 'buildCandidateGraph', notes: 'Builds a candidate packet graph from a plan tree.' },
      { method_name: 'auditReadiness', notes: 'Audits whether operation plans can materialize candidate graphs.' },
    ],
    notes: 'Candidate materialization coordinator. It consumes Planning output and does not resolve policy/default/dependency DSL directly.',
  },
  {
    coordinator_id: 'trusted_inspection_coordinator.v0',
    coordinator_kind: 'inspection',
    public_object_name: 'trustedInspectionCoordinator',
    public_import_path: '@runtime/trusted_coordinators/trusted_inspection_coordinator/index.ts',
    runtime_path: 'runtime/trusted_coordinators/trusted_inspection_coordinator',
    structure: 'foldered_gated',
    expected_methods: [
      { method_name: 'inspectBuildResult', notes: 'Inspects a trusted build result against its frozen operation plan snapshot.' },
      { method_name: 'inspectCandidateGraph', notes: 'Inspects graph shape, candidate references, and body candidates.' },
      { method_name: 'inspectPacketBodyCandidate', notes: 'Validates one candidate body against schema and planned body input values.' },
      { method_name: 'inspectPlanAlignment', notes: 'Checks that candidate nodes align to the plan tree without re-planning.' },
      { method_name: 'auditReadiness', notes: 'Audits planning -> building -> inspection readiness.' },
    ],
    notes: 'Quality gate coordinator. It measures built candidates against the plan snapshot and does not sign, store, or re-resolve the plan in normal mode.',
  },
  {
    coordinator_id: 'trusted_certification_coordinator.v0',
    coordinator_kind: 'certification',
    public_object_name: 'trustedCertificationCoordinator',
    public_import_path: '@runtime/trusted_coordinators/trusted_certification_coordinator/index.ts',
    runtime_path: 'runtime/trusted_coordinators/trusted_certification_coordinator',
    structure: 'foldered_gated',
    expected_methods: [
      { method_name: 'prepareCertificationTicket', notes: 'Creates a short-lived certification ticket from an inspected build result.' },
      { method_name: 'prepareSignatureRequests', notes: 'Converts open certification tickets into dispatchable signature request payloads.' },
      { method_name: 'verifySignedTicket', notes: 'Verifies a signed certification ticket return against the stored ticket hash.' },
      { method_name: 'certifySignedTicket', notes: 'Produces an archive-ready certified packet set after signature verification.' },
      { method_name: 'certifySignedPacketBundle', notes: 'Certifies the existing mutation finalize signed-packet bundle shape against an open certification ticket.' },
      { method_name: 'auditReadiness', notes: 'Audits Planning -> Building -> Inspection -> Certification readiness.' },
    ],
    notes: 'Certification handoff coordinator. It owns tickets, signature request payloads, stable hashes, and archive-ready certified packet sets, but does not write to storage.',
  },

  {
    coordinator_id: 'trusted_archive_coordinator.v0',
    coordinator_kind: 'archive',
    public_object_name: 'trustedArchiveCoordinator',
    public_import_path: '@runtime/trusted_coordinators/trusted_archive_coordinator/index.ts',
    runtime_path: 'runtime/trusted_coordinators/trusted_archive_coordinator',
    structure: 'foldered_gated',
    expected_methods: [
      { method_name: 'storeCertifiedPacketSet', notes: 'Writes archive-ready certified packet sets through the packet store.' },
      { method_name: 'readPacket', notes: 'Reads archived packets or revisions in adapted/raw modes.' },
      { method_name: 'queryPackets', notes: 'Queries archived packet search rows and indexes.' },
      { method_name: 'resolveRevision', notes: 'Resolves preferred/head/requested archived revision refs.' },
      { method_name: 'queryEdges', notes: 'Queries archived packet graph edges.' },
      { method_name: 'exportBundle', notes: 'Exports archive bundle payloads as a low-level storage primitive.' },
      { method_name: 'importBundle', notes: 'Imports archive bundle payloads as a low-level storage primitive.' },
      { method_name: 'auditReadiness', notes: 'Audits packet-store and index access.' },
    ],
    notes: 'Archive seam for packet-store writes, reads, refs, edges, and query indexes. Exchange, Projection, Verification, and Compatibility should ask Archive rather than reaching directly into storage.',
  },

  {
    coordinator_id: 'trusted_compatibility_coordinator.v0',
    coordinator_kind: 'compatibility',
    public_object_name: 'trustedCompatibilityCoordinator',
    public_import_path: '@runtime/trusted_coordinators/trusted_compatibility_coordinator/index.ts',
    runtime_path: 'runtime/trusted_coordinators/trusted_compatibility_coordinator',
    structure: 'foldered_gated',
    expected_methods: [
      { method_name: 'resolvePacketCompatibility', notes: 'Resolves whether one packet envelope can be interpreted by the requested/current schema version.' },
      { method_name: 'adaptPacketForRead', notes: 'Adapts one packet envelope for trusted runtime reads and returns compatibility metadata.' },
      { method_name: 'preparePacketForWrite', notes: 'Prepares one packet envelope for versioned writes without signing or storing it.' },
      { method_name: 'resolveAdapterPath', notes: 'Resolves non-executable adapter path metadata between schema versions.' },
      { method_name: 'resolveCompatibilityProfile', notes: 'Combines core registry truth with Definition packet_compatibility descriptor truth.' },
      { method_name: 'auditCompatibilityCoverage', notes: 'Audits registry, Definition part, and adapter coverage across packet types.' },
      { method_name: 'auditReadiness', notes: 'Audits core compatibility helper, Definition lookup, read, write, and adapter-path readiness.' },
    ],
    notes: 'Compatibility seam for runtime schema-version posture. Core owns adapter logic; this coordinator reports runtime read/write/migration posture and Definition descriptor coverage without storage mutation.',
  },

  {
    coordinator_id: 'trusted_verification_coordinator.v0',
    coordinator_kind: 'verification',
    public_object_name: 'trustedVerificationCoordinator',
    public_import_path: '@runtime/trusted_coordinators/trusted_verification_coordinator/index.ts',
    runtime_path: 'runtime/trusted_coordinators/trusted_verification_coordinator',
    structure: 'foldered_gated',
    expected_methods: [
      { method_name: 'verifyPacket', notes: 'Verifies one packet for structure, compatibility, digest, signature, and signer availability.' },
      { method_name: 'verifyPacketBatch', notes: 'Verifies a packet batch with shared signer context.' },
      { method_name: 'verifyBundle', notes: 'Verifies packet material inside a transport bundle or revision array.' },
      { method_name: 'verifyArchivePacketSet', notes: 'Reads packets through Archive and verifies the resulting packet set.' },
      { method_name: 'verifyPacketLineage', notes: 'Checks parent revision coherence across supplied packet material.' },
      { method_name: 'verifyPacketRefs', notes: 'Checks packet reference closure across supplied packet material.' },
      { method_name: 'verifyCertificationResult', notes: 'Verifies Certification handoff hashes and archive-readiness before storage/import use.' },
      { method_name: 'auditReadiness', notes: 'Audits verification parser, signature, archive, and certification seams.' },
    ],
    notes: 'Verification seam for structural parsing, compatibility reads, digest/signature verification, signer lookup context, ref/lineage checks, and certification handoff verification. It reads storage through Archive rather than SQLite.',
  },

  {
    coordinator_id: 'trusted_exchange_coordinator.v0',
    coordinator_kind: 'exchange',
    public_object_name: 'trustedExchangeCoordinator',
    public_import_path: '@runtime/trusted_coordinators/trusted_exchange_coordinator/index.ts',
    runtime_path: 'runtime/trusted_coordinators/trusted_exchange_coordinator',
    structure: 'foldered_gated',
    expected_methods: [
      { method_name: 'previewImport', notes: 'Normalizes incoming bundle material and combines compatibility, verification, and local archive comparison without writing storage.' },
      { method_name: 'planImportCommit', notes: 'Turns an import preview into a non-mutating commit plan with skip/import/manual-resolution classifications.' },
      { method_name: 'commitImport', notes: 'Commits an accepted import plan through Trusted Archive bundle import.' },
      { method_name: 'exportPacketSet', notes: 'Wraps Archive bundle export in an Exchange manifest and records requested expansion options.' },
      { method_name: 'planMerge', notes: 'Compares incoming packet revisions to local archive state and classifies shallow merge actions.' },
      { method_name: 'previewRebundle', notes: 'Normalizes packet material into a rebundle preview and manifest without storage mutation.' },
      { method_name: 'auditReadiness', notes: 'Audits Compatibility, Verification, Archive, normalization, and merge-planning seams.' },
    ],
    notes: 'Exchange seam for packet movement. It orchestrates Archive, Verification, and Compatibility for import/export/merge/rebundle previews, but Pass A does not commit imported bundles or mutate storage.',
  },
  {
    coordinator_id: 'trusted_projection_coordinator.v0',
    coordinator_kind: 'projection',
    public_object_name: 'trustedProjectionCoordinator',
    public_import_path: '@runtime/trusted_coordinators/trusted_projection_coordinator/index.ts',
    runtime_path: 'runtime/trusted_coordinators/trusted_projection_coordinator',
    structure: 'foldered_gated',
    expected_methods: [
      { method_name: 'resolvePacketProjection', notes: 'Projects an already-loaded packet envelope using trusted packet definition projection descriptors.' },
      { method_name: 'resolveArchivedPacketProjection', notes: 'Reads packet material through Trusted Archive and returns a packet projection view model.' },
      { method_name: 'resolvePacketListProjection', notes: 'Projects archive query results into UI-safe packet list items.' },
      { method_name: 'resolvePacketGraphProjection', notes: 'Projects an archive-backed root packet with archived graph edges.' },
      { method_name: 'resolvePreferredSurface', notes: 'Resolves the preferred UI surface declared by packet projection descriptors.' },
      { method_name: 'auditReadiness', notes: 'Audits projection descriptor coverage for active trusted packet definitions.' },
    ],
    notes: 'Read-side coordinator. Projection asks Archive for packet material and Definition for projection descriptors, then returns UI-safe view models.',
  },
  {
    coordinator_id: 'trusted_resolution_coordinator.v0',
    coordinator_kind: 'resolution',
    public_object_name: 'trustedResolutionCoordinator',
    public_import_path: '@runtime/trusted_coordinators/trusted_resolution_coordinator',
    runtime_path: 'runtime/trusted_coordinators/trusted_resolution_coordinator.ts',
    structure: 'legacy_flat',
    expected_methods: [
      { method_name: 'runStep', notes: 'Planned future public method if Resolution becomes foldered.' },
    ],
    notes: 'Shared DSL executor is intentionally small and flat for now.',
  },
] as const satisfies readonly TrustedRuntimeCoordinatorScaffoldDescriptor[];

export function listTrustedCoordinatorScaffoldDescriptors(): readonly TrustedRuntimeCoordinatorScaffoldDescriptor[] {
  return TRUSTED_COORDINATOR_SCAFFOLD_MANIFEST;
}
