export const PUBLIC_CONTENT_MAX_WIDTH = 1152;
export const ABOUT_BOTTOM_RUNWAY_MIN = 220;
export const ABOUT_BOTTOM_RUNWAY_VIEWPORT_RATIO = 0.34;
export const ABOUT_RAIL_SHELL_HEIGHT_RATIO = 0.68;
export const ABOUT_RAIL_SHELL_MIN_HEIGHT = 600;
export const ABOUT_RAIL_SHELL_MAX_HEIGHT = 1200;
export const ABOUT_RAIL_RIGHT_OFFSET_SPACE_RATIO = 0.5;
export const ABOUT_RAIL_RIGHT_OFFSET_BIAS = 90;
